ORVIT:
  ENABLE: True
  O: 4
  LAYERS: [1,6,10]
  INIT_WEIGHTS: True
  USE_MOTION_STREAM: True
  MOTION_STREAM_ATTN_TYPE: joint
TRAIN:
  ENABLE: True
  DATASET: epickitchens
  BATCH_SIZE: 16
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  MIXED_PRECISION: True
  CHECKPOINT_EPOCH_RESET: True
  CHECKPOINT_FILE_PATH: CP/ek_motionformer_336_16x4.pyth
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [384, 480]
  TRAIN_CROP_SIZE: 336
  TEST_CROP_SIZE: 336
  INPUT_CHANNEL_NUM: [3]
  MEAN: [0.5, 0.5, 0.5]
  STD: [0.5, 0.5, 0.5]
  PATH_TO_DATA_DIR: data/epic_kitchens/
AUG:
  NUM_SAMPLE: 1
  ENABLE: True
  DIFFERENT_AUG_PER_FRAME: True
  COLOR_JITTER: 0.0
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.0
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
SOLVER:
  ORVIT_BASE_LR: 1e-4
  BASE_LR: 1e-5
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01]
  STEPS: [0, 19, 40]
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-2
  WARMUP_EPOCHS: 0.0
  OPTIMIZING_METHOD: adamw
SLOWFAST:
  ALPHA: 8
MF:
  PATCH_SIZE: 16
  PATCH_SIZE_TEMP: 2
  CHANNELS: 3
  EMBED_DIM: 768
  DEPTH: 12
  NUM_HEADS: 12
  MLP_RATIO: 4
  QKV_BIAS: True
  VIDEO_INPUT: True
  TEMPORAL_RESOLUTION: 8
  USE_MLP: True
  DROP: 0.0
  POS_DROPOUT: 0.0
  DROP_PATH: 0.2
  IM_PRETRAINED: True
  HEAD_DROPOUT: 0.0
  HEAD_ACT: tanh
  PRETRAINED_WEIGHTS: vit_1k
  ATTN_LAYER: trajectory
MODEL:
  NUM_CLASSES: 97
  ARCH: slow
  MODEL_NAME: Motionformer
  LOSS_FUNC: label_smoothing_cross_entropy
TEST:
  ENABLE: True
  DATASET: epickitchens
  BATCH_SIZE: 64
  NUM_ENSEMBLE_VIEWS: 10
  NUM_SPATIAL_CROPS: 3
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
TENSORBOARD:
  ENABLE: True
