name: neurmips
channels:
  - pytorch3d
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - _pytorch_select=0.1=cpu_0
  - alsa-lib=1.2.3=h516909a_0
  - antlr-python-runtime=4.8=py38h32f6830_2
  - argh=0.26.2=pyh9f0ad1d_1002
  - ase=3.21.1=pyhd8ed1ab_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h7f98852_1
  - ca-certificates=2020.10.14=0
  - cached-property=1.5.2=py_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2020.6.20=py38_0
  - cffi=1.14.5=py38h261ae71_0
  - chardet=4.0.0=py38h06a4308_1003
  - click=8.0.1=pyhd3eb1b0_0
  - cloudpickle=1.6.0=py_0
  - configparser=5.0.2=pyhd8ed1ab_0
  - coverage=5.5=py38h27cfd23_2
  - cryptography=3.4.7=py38hd23ed53_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - curl=7.77.0=hea6ffbf_0
  - cycler=0.10.0=py38_0
  - cytoolz=0.11.0=py38h7b6447c_0
  - dask-core=2.30.0=py_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.6=h48d8840_2
  - decorator=5.0.9=pyhd3eb1b0_0
  - docker-pycreds=0.4.0=py_0
  - double-conversion=3.1.5=h9c3ff4c_2
  - eigen=3.3.9=h4bd325d_1
  - expat=2.4.1=h9c3ff4c_0
  - ffmpeg=4.3.1=hca11adc_2
  - flask=1.1.2=pyhd3eb1b0_0
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h5ab3b9f_0
  - fvcore=0.1.5.post20210804=pyhd8ed1ab_0
  - gettext=0.19.8.1=h0b5b191_1005
  - gitdb=4.0.7=pyhd8ed1ab_0
  - gitpython=3.1.24=pyhd8ed1ab_0
  - gl2ps=1.4.2=h0708190_0
  - glew=2.1.0=h9c3ff4c_2
  - glib=2.68.3=h9c3ff4c_0
  - glib-tools=2.68.3=h9c3ff4c_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - googledrivedownloader=0.4=pyhd3deb0d_1
  - gql=0.1.0=py_0
  - graphite2=1.3.13=h58526e2_1001
  - graphql-core=3.1.6=pyhd8ed1ab_0
  - gst-plugins-base=1.18.4=hf529b03_2
  - gstreamer=1.18.4=h76c114f_2
  - h5py=3.2.1=py38h6c542dc_0
  - harfbuzz=2.8.1=h83ec7ef_0
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.10.6=nompi_h7c3c948_1111
  - html5lib=1.1=py_0
  - hydra-core=1.0.6=pyhd8ed1ab_1
  - icu=68.1=h58526e2_0
  - idna=2.10=pyhd3eb1b0_0
  - imageio=2.9.0=py_0
  - importlib-metadata=3.10.0=py38h06a4308_0
  - importlib_resources=5.1.4=pyhd8ed1ab_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2019.4=243
  - iopath=0.1.8=pyhd8ed1ab_0
  - isodate=0.6.0=py_1
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jasper=1.900.1=h07fcdf6_1006
  - jinja2=3.0.0=pyhd3eb1b0_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9d=h36c2ea0_0
  - jsoncpp=1.9.4=h4bd325d_3
  - keepalive=0.5=py38h578d9bd_5
  - kiwisolver=1.3.1=py38h2531618_0
  - krb5=1.19.1=hcc1bbae_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libblas=3.9.0=1_h6e990d7_netlib
  - libcblas=3.9.0=3_h893e4fe_netlib
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.77.0=h2574ce0_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libglib=2.68.3=h3e27bee_0
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=3_h893e4fe_netlib
  - liblapacke=3.9.0=3_h893e4fe_netlib
  - libllvm10=10.0.1=hbcb73fb_5
  - libllvm11=11.1.0=hf817b99_2
  - libmklml=2019.0.5=0
  - libnetcdf=4.8.0=nompi_hcd642e3_103
  - libnghttp2=1.43.0=h812cca2_0
  - libogg=1.3.4=h7f98852_1
  - libopencv=4.5.2=py38hcdf9bf1_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=hbc83047_0
  - libpq=13.3=hd57d9b9_0
  - libprotobuf=3.15.8=h780b84a_0
  - libssh2=1.9.0=ha56f1ee_6
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtheora=1.1.1=h7f98852_1005
  - libtiff=4.2.0=h85742a9_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7b6447c_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzip=1.8.0=h4de3113_0
  - llvmlite=0.36.0=py38h612dafd_4
  - loguru=0.5.3=py38h578d9bd_2
  - lz4-c=1.9.3=h2531618_0
  - markupsafe=2.0.1=py38h27cfd23_0
  - matplotlib-base=3.3.4=py38h62a2d02_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.3.0=py38h54f3939_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - more-itertools=8.8.0=pyhd3eb1b0_0
  - mysql-common=8.0.25=ha770c72_0
  - mysql-libs=8.0.25=h935591d_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.6=he412f7d_0
  - networkx=2.5=py_0
  - ninja=1.10.2=hff7bd54_1
  - nspr=4.30=h9c3ff4c_0
  - nss=3.67=hb5efdd6_0
  - numba=0.53.1=py38ha9443f7_0
  - numpy=1.19.2=py38h54aff64_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - nvidia-ml=7.352.0=py_0
  - olefile=0.46=py_0
  - omegaconf=2.0.6=py38h578d9bd_0
  - opencv=4.5.2=py38h578d9bd_0
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1l=h7f8727e_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandas=1.2.4=py38h2531618_0
  - pathtools=0.1.2=py_1
  - pcre=8.45=h9c3ff4c_0
  - pillow=8.2.0=py38he98fc37_0
  - pip=21.1.2=py38h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - pluggy=0.13.1=py38h06a4308_0
  - plyfile=0.7.4=pyhd8ed1ab_0
  - portalocker=2.3.0=py38h06a4308_0
  - proj=7.2.0=h277dcde_2
  - promise=2.3=py38h578d9bd_4
  - protobuf=3.15.8=py38h709712a_0
  - psutil=5.8.0=py38h497a2fe_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - pugixml=1.11.4=h9c3ff4c_0
  - py=1.10.0=pyhd3eb1b0_0
  - py-opencv=4.5.2=py38hd0cf306_0
  - pycparser=2.20=py_2
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pysocks=1.7.1=py38h06a4308_0
  - pytest=6.2.3=py38h06a4308_2
  - pytest-cov=2.11.1=pyhd3eb1b0_0
  - python=3.8.10=h12debd9_8
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.8=1_cp38
  - pytorch=1.7.1=py3.8_cuda10.2.89_cudnn7.6.5_0
  - pytorch3d=0.5.0=py38_cu102_pyt171
  - pytz=2021.1=pyhd3eb1b0_0
  - pywavelets=1.1.1=py38h7b6447c_2
  - pyyaml=5.4.1=py38h27cfd23_1
  - qt=5.12.9=hda022c4_4
  - rdflib=5.0.0=py38h578d9bd_3
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - scikit-image=0.17.2=py38hdf5156a_0
  - scikit-learn=0.24.2=py38ha9443f7_0
  - scipy=1.6.2=py38h91f5cce_0
  - sentry-sdk=1.4.3=pyhd8ed1ab_0
  - setuptools=52.0.0=py38h06a4308_0
  - shortuuid=1.0.1=py38h578d9bd_4
  - six=1.15.0=py38h06a4308_0
  - smmap=3.0.5=pyh44b312d_0
  - sparqlwrapper=1.8.5=py38h578d9bd_1005
  - sqlite=3.36.0=h9cd32fc_0
  - subprocess32=3.5.4=py_1
  - tabulate=0.8.9=py38h06a4308_0
  - tbb=2020.3=hfd86e86_0
  - tbb-devel=2020.3=hfd86e86_0
  - termcolor=1.1.0=py38h06a4308_1
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tifffile=2020.10.1=py38hdd07704_2
  - tk=8.6.10=hbc83047_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.11.1=py_0
  - torchvision=0.8.2=cpu_py38ha229d99_0
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.59.0=pyhd3eb1b0_1
  - typing-extensions=3.7.4.3=hd3eb1b0_0
  - typing_extensions=3.7.4.3=pyh06a4308_0
  - urllib3=1.26.4=pyhd3eb1b0_0
  - utfcpp=3.2.1=ha770c72_0
  - vedo=2021.0.3=pyhd8ed1ab_0
  - vtk=9.0.1=no_osmesa_py38h3850a3d_109
  - wandb=0.12.1=pyhd8ed1ab_0
  - watchdog=0.10.4=py38h578d9bd_0
  - webencodings=0.5.1=py38_1
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - x264=1!161.3030=h7f98852_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7b6447c_0
  - yacs=0.1.6=py_0
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - future==0.18.2
    - lpips==0.1.4
